name: Build Docker

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          args: --no-scripts --ignore-platform-reqs

      - name: Analyse code
        run: composer analyse

      - name: Tests
        run: composer test

      - name: Build
        run: cp -rf .github/workflows/Dockerfile . && docker build -t hyperf .
